### ISSUE TITLE
User cannot start   'Get-CimInstance -className win32_process | select Name,ProcessId,ParentProcessId,CommandLine,ExecutablePath' terminated with code: 1

### ISSUE THREAD

**Issue by Mieekaserra** [Wildlander-mod/Launcher#504] opened 2022-03-16 23:02 UTC
Path in windows has powershell and looks ok. User cannot also start mod organiser from launcher either. He's running windows 10.

Log below

https://cdn.discordapp.com/attachments/953789402587496478/953789557940314192/main.log

User Dean#5920 on discord

**Comment by Mieekaserra** [comment] 2022-03-18 10:38
User EinQuantumTwo#7819 reported same issue today

**Comment by MattLish** [comment] 2022-03-18 10:48
![error](https://user-images.githubusercontent.com/5766291/158989636-74426680-80f2-4ef0-8e1e-0518e21550c2.png)

**Comment by MattLish** [comment] 2022-03-18 11:15
Potentially replace the `find-process` library with this to see if it sorts it

**Comment by MattLish** [comment] 2022-03-18 12:14
This can temporarily be fixed with:

Run `net stop winmgmt` (and `y `if prompted), `Winmgmt /resetrepository` and then `Winmgmt /verifyrepository` should say it's consistent.

The issue is caused by users having a corrupt Windows management repository. Apparently this can happen when migrating from Windows 7 to 10. 
The launcher could potentially automatically repair this in the background if required.

**Comment by MattLish** [comment] 2022-03-18 13:20
We should still swap to https://www.npmjs.com/package/ps-list as the creator has made other solid libraries

**Closed** 2022-06-19 13:18 UTC
Labels: bug
